### Create Menu Item
POST http://localhost:8081/api/v1/anime
Content-Type: application/json

{
  "title": "Jujutsu Kaisen",
  "releaseDate": "2020-10-02", 
  "status": "Finished",
  "type": "TV series",
  "genre": "Action, Shounen",
  "studio": "MAPPA",
  "cover": "https://cdn.myanimelist.net/images/anime/1171/109222.jpg",
  "episodes": 24,
  "duration": 24, 
  "rating": 8.61
}


### Create anime 
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Get Anime 
GET http://localhost:8081/api/v1/anime/1

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Update Menu Item
PUT http://localhost:8081/api/v1/anime/1
Content-Type: application/json

{
  "episodes": 47
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Delete Menu Item
DELETE http://localhost:8081/api/v1/anime/1
Content-Type: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}